exports.INJECTOR_CONFIG_FILE_PREFIX = '.secret-injector.conf';
exports.INJECTOR_CONFIG_FILE_EXTENSION = 'json';
exports.PRIVATE_KEY_CIPHER_VAR_NAME = 'SI_PRIVATE_KEY_CIPHER_TEXT';
exports.INJECTOR_ENV_VAR_PREFIX = 'SI_ENCRYPTED_';
